---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  creationTimestamp: null
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: service2
  namespace: default
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/subpathtester
    subPath: "service2"
status:
  supplyChainRef: {}
